apiVersion: v1
kind: Service
metadata:
  labels:
    name: soft-serve
  name: soft-serve
spec:
  ports:
    - port: 22
      targetPort: 23231
      nodePort: 30022
  selector:
    app: soft-serve
  type: NodePort
