apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nocodb
resources:
  - ../../base/nocodb/
  - cluster.yaml
  - objectstores.yaml
  - offsite-objectstore.sops.yaml
  - scheduled-backups.yaml
  - rustfs-egress.yaml
  - ingress.yaml
  - nocodb-credentials.sops.yaml
  - rustfs-s3-credentials.sops.yaml
  - offsite-credentials.sops.yaml
