creation_rules:
  - path_regex: talos/.*\.sops\.yaml
    key_groups:
    - age:
      - age1njw3753qrva6ezyupp73xnq004f7p5t7cak63k2rs99ghqmsqswqh6n60x
    encrypted_regex: ^(contents|content|TS_AUTHKEY)$
  - path_regex: .*.yaml
    key_groups:
    - age:
      - age1njw3753qrva6ezyupp73xnq004f7p5t7cak63k2rs99ghqmsqswqh6n60x
    encrypted_regex: ^(data|stringData)$
