apiVersion: v1
data:
    adminPassword: ENC[AES256_GCM,data:C//h179hd8vC5XA3ytGivcoo+QY=,iv:55arISQtFxsZ1nFj6/cHm/hwyVf1hP5a1ZuugMQ1gDo=,tag:m7PewaC6NUhl1b9xGGGo8g==,type:str]
kind: Secret
metadata:
    name: grafana-credentials
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVb1lSYzhLY1h2K2d2amh1
            VkVINDVmdWhOSDhJNU82c2pELzFiL2ttL3drCkQ0SHhLRytnSDQ1QjZuNkZybjJi
            dnVva1IyWGNEdWJFNy8xUjAxOENtd1EKLS0tIDNVUmVRUnJBaEcrWHZEOUMzc1RQ
            QXZseGo3bGt5WVk2ZitFUk56TERaYkkKEiMFB334itZDm+7G9isrMJO0pUS7GddM
            2+57u/8V8N8LfM8UykrWQMoqHgzrtlnN0DV+8UC8IAFC8ccwQ3CoWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s4h6ju3m07pmxq396xe9c48fgzq4lk85gm9mhsdlytgmhtevqpjqj57fuw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-10-14T23:39:00Z"
    mac: ENC[AES256_GCM,data:Vc0K2AEeZ3eo0opmRPuwOXcywnnbJOFRgSal0NElAuxo11EWWC2dR/B3X0Q3gbnV9/lUeZ159DLz1iCO2Ve6B/ibtoguTGT4F8IN5eC9HmrRK4cnwGdmMhjcq1TboNXKqJlVMqR9fvyu7UxJDTHlMxn49xtkggw0knbuvgkKjJA=,iv:m1107flfsGDFkNckzLn8Th3zBwLi+5XaBYbKJVuo9Vk=,tag:HhusMJ/Or3KfXyqeiN6/7w==,type:str]
    version: 3.11.0
