machine:
    install:
        extraKernelArgs:
            - net.ifnames=0
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SVFoOUt4V3E4UC94b1Y0
            aVN1WjVLT3JHcVJpekl1QXZVaVVCZmUvSDNrCjhmeEpSSE50SVdiUDAvZDZ4T2Fh
            a0c0dFk3OFFxbjF3L0ZtZzR5RVFYZ1EKLS0tIG05Y29mWDg5S2xqYzd2SSs0c0sz
            OUxJdytvNDJBNlFOKytmS1pXdmN1eDgKyOTFwPpqHIu5O38/3qlR6M+TBbOIB0oj
            8np7RFF8yBtcgnazOinmXkMs1geMUSe7NPCpz3nnlDfaZkE/LXo03Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s4h6ju3m07pmxq396xe9c48fgzq4lk85gm9mhsdlytgmhtevqpjqj57fuw
    encrypted_regex: ^(contents|content|TS_AUTHKEY|environment)$
    lastmodified: "2026-05-16T23:06:02Z"
    mac: ENC[AES256_GCM,data:8ZhheTcJoTEG3yEf/MbhChjtbEzxLOzjWHHm6Oyl87YfEBXaO3n+2GN6AhUxMMUEMZ58mo6iVqu/cVnY5JO2T5Wb/UCVo6i64W1aoBDV5IUcZBz1DfgeRs0UX/JMcWPiaduN6xwuhSvZaWmtbAJpcp1S3cbrrz2Ed/xegImycX0=,iv:byVXkMeGH5i5cc/GwCAHbWmUXwJdYAL0TemCGSHAwZA=,tag:zFiSsH3Ol8/eHxnr85L4CQ==,type:str]
    version: 3.13.0
---
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: tailscale
environment:
    - ENC[AES256_GCM,data:J9tYZuOSbMLj+pXR3sUDctviL+RGzvI1f6OIIRKC/D90,iv:1PhiwtY8fdg9TfgWD6zx/QVmrKT5gfcL9XlJGFxJjug=,tag:p4ATSAVjpBhSaIdCwNScVw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SVFoOUt4V3E4UC94b1Y0
            aVN1WjVLT3JHcVJpekl1QXZVaVVCZmUvSDNrCjhmeEpSSE50SVdiUDAvZDZ4T2Fh
            a0c0dFk3OFFxbjF3L0ZtZzR5RVFYZ1EKLS0tIG05Y29mWDg5S2xqYzd2SSs0c0sz
            OUxJdytvNDJBNlFOKytmS1pXdmN1eDgKyOTFwPpqHIu5O38/3qlR6M+TBbOIB0oj
            8np7RFF8yBtcgnazOinmXkMs1geMUSe7NPCpz3nnlDfaZkE/LXo03Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s4h6ju3m07pmxq396xe9c48fgzq4lk85gm9mhsdlytgmhtevqpjqj57fuw
    encrypted_regex: ^(contents|content|TS_AUTHKEY|environment)$
    lastmodified: "2026-05-16T23:06:02Z"
    mac: ENC[AES256_GCM,data:8ZhheTcJoTEG3yEf/MbhChjtbEzxLOzjWHHm6Oyl87YfEBXaO3n+2GN6AhUxMMUEMZ58mo6iVqu/cVnY5JO2T5Wb/UCVo6i64W1aoBDV5IUcZBz1DfgeRs0UX/JMcWPiaduN6xwuhSvZaWmtbAJpcp1S3cbrrz2Ed/xegImycX0=,iv:byVXkMeGH5i5cc/GwCAHbWmUXwJdYAL0TemCGSHAwZA=,tag:zFiSsH3Ol8/eHxnr85L4CQ==,type:str]
    version: 3.13.0
