machine:
    install:
        extraKernelArgs:
            - net.ifnames=0
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVjBOKzBvdWdUVkxKOW45
            bHJjVXJFbkpJK1VZd2hCSlpPZis5ZnNUckVFCk1oYUVPcnErdEJUN0NtUUVISmw1
            QnBuak1GRU1SeHZsWEQxM2FSa1hmeE0KLS0tIDBtMGpYN0NiOGhpeTMxUklRTkpq
            VWhxUzlva1JwSHcvWUtHVjNoMGJlekEKaPnkiLyoJaslNpkGIKA17AT5md9lSCB9
            W0BzZMMffsI8TVl/Nt73Y0K/3S9FdknQpff9O2IOB0Vuef/L75kV5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s4h6ju3m07pmxq396xe9c48fgzq4lk85gm9mhsdlytgmhtevqpjqj57fuw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-16T22:50:49Z"
    mac: ENC[AES256_GCM,data:ZluB1mz9cq0r9PYfPzRpoTFYaUtEPxx7fwmQrKvDxuAujyaKSKOdGFPW0+tlP06SLuIiecoTzgGnL9UxSk4voOsbCu+Sj7pqfQSNis00vylj7+b6vy+fGLb8e7p/u+2jaoj8sh/LBYRaCgZv0lnQS8or1cCBu/fECZCuiyd72sk=,iv:6mxrFbOacAr8D8UnkUsse8JBLbAbQAayuYEvyeeVY60=,tag:/HwDo4KG5kdInUW2Lo6SGQ==,type:str]
    version: 3.13.0
---
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: tailscale
environment:
    - TS_AUTHKEY=tskey-auth-YOURKEYHERE
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVjBOKzBvdWdUVkxKOW45
            bHJjVXJFbkpJK1VZd2hCSlpPZis5ZnNUckVFCk1oYUVPcnErdEJUN0NtUUVISmw1
            QnBuak1GRU1SeHZsWEQxM2FSa1hmeE0KLS0tIDBtMGpYN0NiOGhpeTMxUklRTkpq
            VWhxUzlva1JwSHcvWUtHVjNoMGJlekEKaPnkiLyoJaslNpkGIKA17AT5md9lSCB9
            W0BzZMMffsI8TVl/Nt73Y0K/3S9FdknQpff9O2IOB0Vuef/L75kV5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s4h6ju3m07pmxq396xe9c48fgzq4lk85gm9mhsdlytgmhtevqpjqj57fuw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-16T22:50:49Z"
    mac: ENC[AES256_GCM,data:ZluB1mz9cq0r9PYfPzRpoTFYaUtEPxx7fwmQrKvDxuAujyaKSKOdGFPW0+tlP06SLuIiecoTzgGnL9UxSk4voOsbCu+Sj7pqfQSNis00vylj7+b6vy+fGLb8e7p/u+2jaoj8sh/LBYRaCgZv0lnQS8or1cCBu/fECZCuiyd72sk=,iv:6mxrFbOacAr8D8UnkUsse8JBLbAbQAayuYEvyeeVY60=,tag:/HwDo4KG5kdInUW2Lo6SGQ==,type:str]
    version: 3.13.0
