apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: audiobookshelf
  namespace: audiobookshelf
  annotations:
    tailscale.com/hostname: rammus-audiobookshelf
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: tailscale
  rules:
    - http:
        paths:
          - backend:
              service:
                name: audiobookshelf
                port:
                  number: 3005
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - abs.tn.example.com
      secretName: audiobookshelf-cert
