apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
spec:
  values:
    operatorConfig:
      hostname: rammus-tailscale-operator
      defaultTags:
        - tag:rammus
        - tag:k8s-operator
