apiVersion: v1
kind: Secret
metadata:
    name: oauth-credentials
    namespace: infrastructure
stringData:
    values.yaml: ENC[AES256_GCM,data:IoKOpRB1SyumCzXcqTtRSgOOOtOTCAz2D+dj9GZw3HBQOJft2wMeF/wpEWGLnkfnzCfJtJ2poiyCzlbRcRjZjvg7XUG1IKBvDuLINSLLMMM5ouw3ztoAfGLGdjSqi3cwgstl9gSdAothLyh+tW617fSEpZTYhrzhMnX+WKuYDp7j95C6Bbc=,iv:0sMSptdWjlQoS0Da/W2qrzujS6nURjXS/HV/85XKDeM=,tag:qh/9cmVvCsdSThXyIW7q0g==,type:str]
sops:
    age:
        - recipient: age1njw3753qrva6ezyupp73xnq004f7p5t7cak63k2rs99ghqmsqswqh6n60x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWaFBISHpSeTNiVmFIUGZt
            UXUyZmh5dG4rVk9EOGxZUUVyTzBwWUZ6bnpBCk45RE5SbWQzbWE5dFZuWERLU3gw
            YTRYbDNjM3QyTUhkcDBLYTRYUjUzYTQKLS0tIDZzS21OR0FuQmpVbDNBc2FjdXQ3
            eUVJNnltWVRYQlJwT0Z4MG1JMWh2S00K4/H1NL5r+aH1Fn7rH78tUyZXepH1eP5U
            zW0f8v4nhh5VVGYr/wpjlNd/Wo+OW2QpNffBQpxYAal0C92+hZnxYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T20:44:05Z"
    mac: ENC[AES256_GCM,data:83iTFEu36ZBovAOay1tTWuQPx5QlT1bb03N9hAGPoM9Kxz7vKFjSUv9OcEsCiYbwxa4AIabhAElQnvQAv+LONnHKiWa2jUickiQnRBeLKKJMtj4mPvmSppY3dAZ8WmjE2Ne8UoiJ8e86ry3n4AhlnmI3wKllkOJplNR5hX3bSGI=,iv:uTusXlxZdH1VGe5Tp0uVPwpaJfbbi4yCpph6ytbsYDM=,tag:xL/yAD3Z7vHRmWbolzUkeg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
