apiVersion: v1
kind: Secret
metadata:
    name: oauth-credentials
    namespace: infrastructure
stringData:
    values.yaml: ENC[AES256_GCM,data:tTwNGn4rZpQr49VR/VzKNRUS+2fXE8ZKTieLH2xeqUEWjDJHK9/e0T6UDwv+rKFtUEI4gZWlS+Yp1FrYuU5VrahF5EeUWJTg52784v0Yr5GjTLqinir82/KrTdmg0VnTyOPThdcy2wQQgSYvYLy0qAEVKVeZ+Efdfg==,iv:IKUUF/+E05tI29NTeKPEejYoAcxAO23qW2CtkT+bRbQ=,tag:I1Wzs/QvLgJznKLSsvsXQw==,type:str]
sops:
    age:
        - recipient: age1njw3753qrva6ezyupp73xnq004f7p5t7cak63k2rs99ghqmsqswqh6n60x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VjBvVFdkQ0RidUlBWjVF
            TVYrOEtkbC83MzRZTnNVQWJOYU1SbmdHWmhRCkFVMi9ZTFNLcUtWZjl2UWI5bVhZ
            YjZTOEljdUl2T0E4cWg4SVM5Z0RibUkKLS0tIGN2RkJvVGx2ejEyTWc4c0ZnOFVn
            eXhSclk0UnBwVHFUN3lpMGlTS2VNb1UKdN39UK6h6UZg4WyEX1lGody4U+eGqIUh
            ka3eJUTQjJve//V1r50BbP9rtB2t9WyNbONzvupc72lP5GveiPryEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T21:05:46Z"
    mac: ENC[AES256_GCM,data:XHAgSgVHw8KPvt1R62fiWKDmMszOWMOQUjxLz4K3nScRrHAwgDSAHJk2AaqnTO8L6ZuyF61QFj3/A3IfGnBQAgoYq1ZWlKIvO/Exc5Vmqs+AqmW6sAJ3jUBD3BKEtobbTi0eGYA5gMtPC/suPU1oXgMTlBYhIm36kiij2CUhZbA=,iv:365+DXJrtE+mNCPDrhpifJsw6zbCjcwCX55EPnW8S4Q=,tag:BgaGDauRDRnxcAZLHRK4mA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
