apiVersion: v1
kind: Secret
metadata:
    name: oauth-credentials
    namespace: infrastructure
stringData:
    values.yaml: ENC[AES256_GCM,data:0olmTFgrDWm1TqeQaZGSiHdt7sBZzBBaYzIiOppSv/3+x89N6s8rx2/dnzLQDNDDKdLcIuphLedprnriPclI4kVABWCDe18lsGWOTNUvtMR9jPk/K/e7TCaBzb3LxUIsM5cbYoacTqMJLRglAJ6HXVfE346dl4GtP9DNqjuWbR5WS35dhBEwgxv3Dv5PJZsiz04j3J/OjMmLhMbiefnj,iv:mlA46lvVFiYy4AZEgVd9AOPvQrt6q9eTkwyQyHpqCEA=,tag:vryGHqzGbC3laUg2+LIiCA==,type:str]
sops:
    age:
        - recipient: age1njw3753qrva6ezyupp73xnq004f7p5t7cak63k2rs99ghqmsqswqh6n60x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWUh0dVp2dmFwbDNaUXda
            TWxHbFZpRmN2V3NBdUNyNVB0dE9Od2JBN2lrCjZMeUU4cjB2ajRjdEJNbytXMnZZ
            YXVkMGh3QWdvWXl4blh4VVg0M0NBWEUKLS0tIENSZEtVUGRXb3crbmRlQWZZV2lk
            QzJlekJUVkFhWitoZVhQczhLdHo1bE0KSWfdj5yTHx0+ujeAHi6Wmdvh7wJvdfyR
            9+3j+3PWn58y/Qk/NKZLKqi09S7UKyv++Ycsu4yopS6Zm2opvxv2sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T21:23:55Z"
    mac: ENC[AES256_GCM,data:i6t7hC6FLyr+Wz5SMgPv4UdQaSho/6fxhVl6FucmU3KktHJFpBmg8D3ZUq7Fj2EfRaoGGg5ld34x2M/625zbkv1srUY53NobeaRE3Lgevn+eirBV04L6utWVRCcH4eYMEMe+wfe34zIWvpmC6Qq6imz6U+vhmMu3haXOI5JwA2M=,iv:BzEWtoV2eUC+7UW5W5VLChffuUUq3k78GEebsvC2aPQ=,tag:GbJn2Jw/0g5XkybSyDAyTg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
