apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: sysadmin-homelab_letsencrypt@nwo.pm
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      # user dns01 instead of http01 because it supports wildcard certificates (c.f. https://letsencrypt.org/docs/challenge-types/#dns-01-challenge)
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
