apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/rustfs
  - rustfs-credentials.sops.yaml
  - teable-s3-user.sops.yaml
  - provision-job.yaml
patches:
  - path: service-patch.yaml
