apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  values:
    grafana:
      ingress:
        tls:
          - secretName: grafana-tls
            hosts:
              - gap.nwo.pm
