apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:yM6NwUjlaY884MXMDNP/kOkb1hNdZpplomvmKZ/EvRkCerPV/XMprIUCKfkWKIYE4l+e/OGv4VBB4pk6FsbIF2Rr71g5bjh5UW9JSeH+yZYu87kw7FllAC+H377YYrH9GfveUianenMwBPveSt2ri2a3G2qV9SoAt0BoDQ==,iv:TnyhcpsjRphayw6OIDVDo3RZbxDR3EAxVL6OUwiOaPk=,tag:XNE6OShVbJ9s7nX8n12qAA==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzc3hTWUU4MjQ1Y0xaUDVM
            OFZaNnd6WmRnREM0YmtDZUMxUFVXay8wZVh3CnhQMk5QZ1NtZ3BoQ0JKaXVBTW9P
            Y2FvV1pEUWNtb21zdXBCa210UTNONzQKLS0tIDBHeEdKNGI1VjI2eTRaT3NTdE1w
            TzEzaUx6dXBIWXRKMkpMNWY3b3c1eFUKEo3jmOIwIDlJ9Ih3rbiCTQ5bDD4eStMb
            HCQNtVL9pBwge1iXVgmjv06n2vdXCeiNb/t/HJoaCrXh7qolEZkCIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s4h6ju3m07pmxq396xe9c48fgzq4lk85gm9mhsdlytgmhtevqpjqj57fuw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-11-25T01:33:32Z"
    mac: ENC[AES256_GCM,data:/fUNlrY7apN19XPbmI4gsoeL+0GL/Pzyh+ANcQ5fy6KiTuzuIHKPz1STF2Vue3Wuq2uBRBZgoRc1hBwpQfjKxAvPZKmx6N700b5i2K6suOr7Zgx37VmdbtpPzRjLqdS2Sv/Xhqa9u4Q4Vck/pmdFWZ3Fm+bVQev7lzfvOUBSXRw=,iv:lvk5NB7tp7zdqfS2r04AHwvXprNZIsC3pnrzN5LcvoM=,tag:qP3+YkwAZBZ1EOv+XmF7sw==,type:str]
    version: 3.11.0
