apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: linkding
type: Opaque
data:
    credentials.json: ENC[AES256_GCM,data:oayu0YdinRORGGQDiwcVcVOz+IYLbhuQ2LCylVLoGMaDa7MX47V4y49SAvLA6t3PJdMQ8f6ujmuMZgemkT8tO85ra0VonvneFeTHQHSdh/nziwFMwV78TRNoMU8zmqu5ZnT1/IuN+f4BslUKUU2+kspMQLddEDrpz7X6x4IjRczsnd1pUf+am+Wmkx4vpj10Jihapz9/SJC2BL6zBqrtZ3XLGnsXn2b5+214pisPVEXqcWD4sraGewh9KYi+UZ4MXTjim2p37dO5HnAghm5J59zwfD+AmBPQBk61aSdK6gLUT31DeDzPe5uq+BI=,iv:d2zEc3y5fQC7AyWD3rJxz1jS0y6jejB6t0IQgdeq4Js=,tag:1xeARLVww7jkAXdfFFDzPA==,type:str]
sops:
    age:
        - recipient: age1njw3753qrva6ezyupp73xnq004f7p5t7cak63k2rs99ghqmsqswqh6n60x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdE5Yd2dmZnVJQTF5c0p3
            N0xxeGI3Q0VONGpxOHlmdG41OHd5TDNralhZCnNoWlRqYnFGVU5oM21NbE8ya3Jk
            QjlOVENCTkNhZU5oblAyaklnY2pkVTAKLS0tIFYvK1B5N01lZ0p6bnZyV0NHSlU5
            QlVnZXFVK2ovcXVQaVNHbExMZGtjRlkKpZD1Eb5+jJeQyPEHAdATmre/4rHJ1kQT
            8YT/1bvVo2qauAF8kVBs3bk+cftvH1alyYWtZCB4AyJtV5SuMHltwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-13T22:24:33Z"
    mac: ENC[AES256_GCM,data:JMuwfkT3WbKNXJ3YejXvIXUhpvnnG96DnSVD+zSLCyL21f43l1gM1dwSNPwsP+uoVIHFBfjvohGJOeXk5hNMrKAR22Hv1p0Q7gDcp7xn/x51MqORwBEjSQqQRgwAl3zsS3RbyeQDXkmaKI6bD9sj+0YGe9ZsVQDFI13rSNXfNKo=,iv:HdCf1yId8LFGmnba35L7oFk0fanJDl6sA3NWyFR+GJg=,tag:mqwfUNfY+4QPyG/enHz4WQ==,type:str]
    encrypted_regex: ^(credentials.json)$
    version: 3.11.0
