apiVersion: apps/v1
kind: Deployment
metadata:
  name: rustfs
  namespace: rustfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rustfs
  template:
    metadata:
      labels:
        app: rustfs
    spec:
      containers:
        - name: rustfs
          image: rustfs/rustfs:latest
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: rustfs-data
              mountPath: /data
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: rustfs-data
          persistentVolumeClaim:
            claimName: rustfs-data-pvc
