apiVersion: apps/v1
kind: Deployment
metadata:
  name: rustfs
  namespace: rustfs
spec:
  replicas: 1
  strategy:
    type: Recreate
    rollingUpdate: null
  selector:
    matchLabels:
      app: rustfs
  template:
    metadata:
      labels:
        app: rustfs
    spec:
      containers:
        - name: rustfs
          image: rustfs/rustfs:1.0.0@sha256:8cc9801755448b71a786705ce76692c77e14936cccd87cf2fc31842e58f4d1ff
          envFrom:
            - secretRef:
                name: rustfs-credentials
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: rustfs-data
              mountPath: /data
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: rustfs-data
          persistentVolumeClaim:
            claimName: rustfs-data-pvc
