apiVersion: v1
data:
    api-token: ENC[AES256_GCM,data:yXHu/4LTxIXZ3ghqbi2nqcat/5PTv83keFDZpR9vHONDs0q/gfzm5w+PrATYK5lycvx1Y8kPAgk=,iv:avFOGFa95wBDR/k55f/3b9/IQf96i2YYWhPZO3VgQLI=,tag:3kxtgUHlzBxifD5DzQLPUg==,type:str]
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: infrastructure
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVjZ3eTFKaU1zaUtaM1pC
            VWFGOUo0N2FhSkRHOEoxMGJLK3FldWE4K3pnCkMvU2Z1UTJGWHAvT3dJdVQ4ZEN0
            QzQ2SnhJbTRRakJleFdoOWFoL1IzMUEKLS0tIDRBOVk1clE5ZWUydks2YjNxdDEv
            ZW95aWcvYThqaVhXdHp0QjM2eUJEN1kKgS/IyP3VfeyhVlt9DP1BX2Br0M888IhC
            JEBE863D6sGAGz/ezK2Abv+j0h8OnULRjwiWpTdptJ4gSQ7QKGCAyA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s4h6ju3m07pmxq396xe9c48fgzq4lk85gm9mhsdlytgmhtevqpjqj57fuw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-10-17T17:41:54Z"
    mac: ENC[AES256_GCM,data:+4pn3uC8DDFUNTFFscCJRqCluSSRTPjsgHUPnL3Wn1j7702TR/724pxzW0bcyfX/PWx5G80Z7BL7dOmVPpTlf6G6Gbh2Dnvk4igI4mfGX+vNyjrt1mzYSFiEMbxzyoz3m8WjOTqA+d+QzHb71MivrWevnKF1L+zap6XW/sf7rdc=,iv:eygj9YCzq7+6x1cavJ5S4dJGyZgHR4KVtzP64lrAYHQ=,tag:NIynsrDc+ZGmd6twM9nLww==,type:str]
    version: 3.11.0
