#!/usr/bin/bash

set -euo pipefail

mise_cmd=$(which mise)
echo "mise path is: ${mise_cmd}"
if command -v $mise_cmd > /dev/null; then
  $mise_cmd trust && $mise_cmd install
fi
echo "🎯 scripts/setup done installing"
exit 0
