apiVersion: v1
kind: Secret
metadata:
    name: oauth-credentials
    namespace: infrastructure
stringData:
    client_id: ENC[AES256_GCM,data:KRbB0SLfZdduc9VI0r7QcG4=,iv:S1ABMVn/59ZaV8G2Gv9DfVSlKMk0pyXSmF23V6mSuJk=,tag:32g/CjY7uqmZw6IxVq9C5A==,type:str]
    client_secret: ENC[AES256_GCM,data:VIH+0Ns6UQDBvUi1cfiymLsB9TUp2Wvvdf2blnsLjqgIwu1Nt1Yck2fV096ICG/pPRk9cIznnTJfoFNrffOh,iv:zqC7oQSVw9Fy5T7HUwTaLOLz3pnklfvAqw4fQweMC6g=,tag:JOZhOcrb5nqW+nHxNQzGWw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3QmRWMWJhZzZWcHQ4UG5o
            eGxpUVYxWWJFRXQvMzJkMW5CS2xXaGMzRlgwCmoxVWY5NVdRc1Rnem42L3VCNVl5
            aHhESnJsbk1lOGwyenBndGg2OUM2ZTAKLS0tIG5Ody9SaWNmSzRUR25CSkRqejNq
            c3dMS2ZiU3VtVlpXVzFTbnl3aG95M3cKL+wZM5W3uUouMaxVmN+2zqj5XfITwQKF
            Hy5XEzvKz310fpRldaOYv18o1yirspN97MEI8KUH8Iw4LbgZ1j6WmQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s4h6ju3m07pmxq396xe9c48fgzq4lk85gm9mhsdlytgmhtevqpjqj57fuw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-15T10:49:06Z"
    mac: ENC[AES256_GCM,data:JB2BNGp9OzLrIDQaARFBqPgZTtaiz4mLRzF7xjVE/PrbqI6ixNPlyTy82byS+q91H7r/jNYOfCPgG0DPcO3wUaDkDwIlWbJ4ewP/EN5kDVQ6gShNgq8DKEhhUmXokSiKi8tmp5+bk0c1jJa/1prnte9sA3rOlqI9LjCHfxvbZxw=,iv:H9dFRsL54A7RIkvMt7/a7Uy+q3mRDTxYf6+M3yNmOL4=,tag:ZelC/1O3pHNE5gEWtU7OuQ==,type:str]
    version: 3.12.2
