apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linkding
  namespace: linkding
  annotations:
    tailscale.com/hostname: rammus-linkding
    tailscale.com/tags: tag:rammus
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: tailscale
  rules:
    - http:
        paths:
          - backend:
              service:
                name: linkding
                port:
                  number: 9090
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - ld.tn.example.com
      secretName: linkding-cert
