apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linkding
  namespace: linkding
  annotations:
    tailscale.com/hostname: rammus-ld
    tailscale.com/proxy-group: default
spec:
  ingressClassName: tailscale
  rules:
    - host: ld.tn.example.com
      http:
        paths:
          - backend:
              service:
                name: linkding
                port:
                  number: 9090
            path: /
            pathType: Prefix
