apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:s99KrysJyUE=,iv:9CnvkMq7LbgTag4/xpkGtNy8s96dNFwpZ8MiPTemlFA=,tag:3fhnP+gjGIGsuAhETeNflQ==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:oal1tsum7Tk=,iv:77L+SYhgHTCngHBNSHHXb8xfVT9ysT25s0w9c4tC48s=,tag:kV5lI8dMnPsBZrQXBfifng==,type:str]
kind: Secret
metadata:
    name: linkding-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdGZ4YkxxZEJNQU5CSDA1
            d2xjQzFHT3B1eHlHWkFFS1Y3L3RZUDdlSkhNCk83cm9lODMxY3BQdkM5QXlrQUJq
            WEtKbkpyL3lDYzFqdGZRam5ON0NtTXMKLS0tIG1ZcjNwa3BkRnBVVG1mekgzMFRF
            TGJvNTRpaDgxVWpqWmlNcVhQTVdhYXMKN/cSRNDU3HRx6P/ILSARRh8ObKyKMlK2
            QO5E8o2elEZ+8OInAjaa2M4OrmtuzH8bQRDDiELdCIHltK+0qJhAuQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s4h6ju3m07pmxq396xe9c48fgzq4lk85gm9mhsdlytgmhtevqpjqj57fuw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-10-14T01:16:14Z"
    mac: ENC[AES256_GCM,data:ia58j43/xjK/LFeBgGZPhnkDHjq3REjtKKdWr74c1ltu+blQZFbFoZxxAFEZpBDrEzimbBPDRN4Z8wlGrQUJxB8NAHbtg2OBVowPDClSxs3f60MENhUKRdv3iQuxmpLoKCZb8dLaJiUQeXBy0MLuDmfNGfIK/up9sZPBe4HKKew=,iv:6Ohg5WJm6u42O3b0+JyT1u8k38mQualiue1pQmWOGr0=,tag:XP9MKSEeRLCUNsaqnpq5Wg==,type:str]
    version: 3.11.0
